# Версия docker-compose
version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
          - "80:80"
        volumes:
          - ./docker/hosts:/etc/nginx/conf.d
          - ./:/var/www
        depends_on:
          - app
    app:
      build:
        context: ./
        dockerfile: ./docker/Dockerfile
      volumes:
          - ./:/var/www
      depends_on:
      - db
    db:
      image: mysql:8.0
      cap_add:
        - SYS_NICE
      restart: always
      environment:
        - MYSQL_DATABASE=app
        - MYSQL_ROOT_PASSWORD=adergunov
      ports:
        - '3306:3306'
      volumes:
        - ./docker/db:/var/lib/mysql
